# Generated by Django 4.2.16 on 2026-05-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purepick_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='custom_allergens',
            field=models.TextField(blank=True, default=''),
        ),
    ]
