# Generated by Django 4.2.16 on 2026-05-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purepick_core', '0002_healthprofile_custom_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='ai_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='personal_warnings',
            field=models.TextField(blank=True, default=''),
        ),
    ]
