# Generated by Django 4.2.16 on 2026-05-28 21:29

from django.db import migrations, models
import purepick_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('purepick_core', '0005_fcm_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedproduct',
            options={'ordering': ['-saved_at']},
        ),
        migrations.AlterModelOptions(
            name='scanrecord',
            options={'ordering': ['-scanned_at']},
        ),
        migrations.RenameIndex(
            model_name='allergytag',
            new_name='purepick_co_name_b484dd_idx',
            old_name='core_allergytag_name_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='purepick_co_token_100994_idx',
            old_name='core_resettoken_token_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='scanrecord',
            new_name='purepick_co_user_id_568514_idx',
            old_name='core_scan_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='scanrecord',
            new_name='purepick_co_barcode_807fad_idx',
            old_name='core_scan_barcode_idx',
        ),
        migrations.RenameIndex(
            model_name='skinconditiontag',
            new_name='purepick_co_name_a4dba1_idx',
            old_name='core_skincondtag_name_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='purepick_co_email_f402d4_idx',
            old_name='core_user_email_idx',
        ),
        migrations.AlterField(
            model_name='allergytag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=purepick_core.models._token_expiry),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skinconditiontag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='savedproduct',
            index=models.Index(fields=['user', '-saved_at'], name='purepick_co_user_id_592b55_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='purepick_co_usernam_ba527c_idx'),
        ),
    ]
