# Generated by Django 4.2.16 on 2026-05-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purepick_core', '0006_alter_savedproduct_options_alter_scanrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('shampoo', 'Shampoo'), ('cleanser', 'Cleanser'), ('moisturizer', 'Moisturizer'), ('sunscreen', 'Sunscreen'), ('serum', 'Serum'), ('conditioner', 'Conditioner'), ('body_wash', 'Body Wash'), ('toner', 'Toner')], max_length=50)),
                ('safety_score', models.IntegerField(default=95)),
                ('image_url', models.URLField(blank=True, default='')),
                ('buy_url', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='best_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_streak_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
