# Generated by Django 4.2.16 on 2026-05-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purepick_core', '0007_cleanproduct_user_best_streak_user_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='gender',
            field=models.CharField(blank=True, default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='skin_type',
            field=models.CharField(blank=True, default='Normal', max_length=50),
        ),
    ]
