# Generated by Django 4.2.16 on 2026-05-29 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purepick_core', '0006_healthprofile_age'),
        ('purepick_core', '0008_healthprofile_gender_healthprofile_skin_type'),
    ]

    operations = [
    ]
