# Generated by Django 4.2.16 on 2026-05-30 12:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purepick_core', '0009_merge_20260529_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('condition_score', models.IntegerField(default=3)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('am_routine_done', models.BooleanField(default=False)),
                ('pm_routine_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_logs', to='purepick_core.user')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
