web: python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn purepick_core.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
worker: celery -A purepick_core worker -Q default --loglevel=info --concurrency=2
worker_ml: celery -A purepick_core worker -Q ml --loglevel=info --concurrency=1 --pool=solo
